language: node_js
node_js:
  - "stable"
skip_cleanup: true
install:
  - npm install --save-dev webpack
  - npm install --save-dev webpack-cli
script:
  - webpack -p --config ./webpack.config.js
  # - npm run build
  # - npm test
