language: node_js
node_js:
  - "stable"
skip_cleanup: true
install:
  - npm install webpack -g
  - npm install webpack-cli -g
script:
  - webpack -p --config ./webpack.config.js
  # - npm run build
  # - npm test
